#!/bin/bash
# This hook is sourced after every virtualenv is deactivated.
# source postdeactivate hook


# Check if the Projects Folder Exists
# -----------------------------------
if [ -n "$_PROJECT_DIR" ]; then


    # Look for a hook file
    # --------------------
    hook_file=$_PROJECT_DIR/bin/postdeactivate


    # Trigger the hook if it exists.
    # --------------------------------------
    if [ -f $hook_file ]; then
        source $hook_file
    fi


    # Remove this Environment Variable
    #      (it is set in postactivate)
    # --------------------------------
    unset _PROJECT_DIR


fi
