#!/bin/bash
# This hook is sourced after a new virtualenv is activated.


# Get the name of the Virtual Environment argument passed
# -------------------------------------------------------
new_project_name=$(echo $VIRTUAL_ENV | awk -F'/' '{print $NF}')
new_project_path=$PROJECT_HOME/$new_project_name


# Create the directory if it doesn't exist
# # --------------------------------------
if [ ! -d $new_project_path ]; then
    mkdir -p $new_project_path
fi


# Add Project to Virtual Environment
# ----------------------------------
add2virtualenv $new_project_path


# Go to the Virtual Environment Folder
# ------------------------------------
if [ -d $new_project_path ]; then
    cd $new_project_path
fi
