#!/bin/bash
# This hook is sourced after every virtualenv is activated.
# source postactivate hook


# Contains the absolute path to Project
#
#   @note:  This will not return the same as postrmvirtualenv
#           even though they have the same variable name.
# -----------------------------------------------------------
virtualenv_project_dotfile=$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME


# Does the VirtualEnvironment From Stdin
# -----------------------------------
if [ -s $virtualenv_project_dotfile ]; then


    # Export the this project directory for use in other hooks
    #       (eg: postdeactivate)
    # --------------------------------------------------------
    export _PROJECT_DIR=$(cat $virtualenv_project_dotfile)


    # Look for a hook file
    # --------------------
    hook_file=$_PROJECT_DIR/bin/postactivate


    # Trigger the hook if it exists.
    # --------------------------------------
    if [ -f $hook_file ]; then
        source $hook_file
    fi


fi

# Go to the projects folder
#   (If the path can't be found it will tell us)
# ----------------------------------------------
cd $PROJECT_HOME/$(basename $VIRTUAL_ENV)

