#!/bin/bash
# This hook is sourced after every virtualenv is activated.
# source postactivate hook
_HOOK_PATH=bin/postactivate
_PROJECT_FILE=$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME

if [ -s $_PROJECT_FILE ]; then
    export _PROJECT_DIR=$(cat $_PROJECT_FILE)
    _HOOK=$_PROJECT_DIR/$_HOOK_PATH
    [ -f $_HOOK ] && . $_HOOK
fi

PS1="\n┌─[ \e[1mWorking On\e[0m ]──[ \e[1m\e[93m`basename \"$VIRTUAL_ENV\"`\e[0m\e[0m ]\n├[ \e[32m\e[1m\u\e[0m\e[0m ]──[ \e[1m\e[94m\w\e[0m\e[0m ]\$(current_git_branch)\n└──▶ \e[1m$\e[0m "
