#!/bin/bash
# This hook is sourced after every virtualenv is activated.
# source postactivate hook
_HOOK_PATH=bin/postactivate
_PROJECT_FILE=$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME

if [ -s $_PROJECT_FILE ]; then
    export _PROJECT_DIR=$(cat $_PROJECT_FILE)
    _HOOK=$_PROJECT_DIR/$_HOOK_PATH
    [ -f $_HOOK ] && . $_HOOK
fi
